language: node_js
node_js:
- node
jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    script: jest && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      && rm -rf ./coverage
  - stage: Transpile typescript
    node_js: node
    script: rm -rf dist; tsc
deploy:
  provider: npm
  email: 'jarvisam@gmail.com'
  api_key:
    secure: QL2MfcWfqofr9hxmHdpvZxuSZH2own9mx3xHt0fJpq4w9UG9f02vb9WDZrxJNQGhiS5Ys3JafYexE51gvuPi3j7mkxtjUgTKuNEPfd7fPlELKMDr7hXCl+i8Hk0/nWghvvD2akc2mW+CDxaQsYtyAc2WfLE7IDgon0SXyOJj5X2T889QZ281/Sudk/KN3R1MUZk7d2Z1Rcj18DRIGE3gaO3TbiJdwTligmNSh/Q1RDCnad/AwOEL6zsnPRSfH34GlnwarDesxZ7iIcMQCWOmAbY7LR9XofoTTYkYhJK971iq8VoF8v526OfuMkZ77KLDU14bq98iNG3C8vk/rTVfYW67sTD/zLxBFnro1Rt/OuMURdLhUu79mAUxQIf8Vf1ScICHIxY3hwUBvSqC56X5Zh3EMctIakzWSsC8qy71Hh0SQ2Tqg+vjBBz/qMF5xYhS31O73v5MTCJ0jQawSrAqiv3zRoF6uMXNuEt0XGNGPqrlUeVQgtXlJL3Rrh7sJtN5NA6F/6kBDabudBycGyXzyfzQC4M50zzr4aLLZddlMEGAXAxLVT21dboRb5EAqawNZqYGaSk41tecM56fHw4jBhps+vUUyirpRG6uEy0dDQ0XDtegsCtIheuQe7iScJaFeMQNjyUJawK3fdmFfmK04SHJ3YgWDvQ2creXn86UcWk=
  on: 
    tags: true